name: eosdart_ecc
description: Elliptic curve cryptography functions in Dart. Private Key, Public Key, Signature, AES, Encryption, Decryption
version: 0.4.3
homepage: https://github.com/primes-network/eosdart_ecc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bs58check: ^1.0.2
  pointycastle: ^3.0.1
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.17.4
